.TH docbook2odf 1  "April 17, 2017" "version 0.244" "USER COMMANDS"
.SH NAME
docbook2odf \- Convert a DocBook document to OASIS OpenDocument format
.SH SYNOPSIS
.B docbook2odf
[\-\-help] \-\-input\-file [\-\-output\-file]
.SH DESCRIPTION
docbook2odf is a toolkit that automaticaly converts DocBook to OASIS OpenDocument. Conversion is based on XSLT, which makes it easy to convert DocBook to ODF, ODT, ODS, and ODP, as all these documents are XML based.
.PP
The result is provided in one zipped ODF file (.odt/.odp/.ods) with all required content. docbook2odf actually universally converts
to these respective formats.
.SH OPTIONS
.TP
\-V
display the version of docbook2odf and exit.
.TP
\-\-input\-file
specify input DocBook filename.
.TP
\-\-output\-file
specify output OpenDocument filename.
.TP
\-\-force
overwrite existing output filename.
.TP
\-\-debug
show debug messages.
.TP
\-\-quiet
quiet (no output).
.TP
\-\-help
prints short help.
.SH AUTHOR
Roman Fordinal (fordinal (at) webcom.sk)
